CREATE DATABASE memo_app;
\c memo_app
CREATE TABLE memos (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  info TEXT NOT NULL,
  tag TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
